[project]
name = "memvid-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastembed-gpu>=0.7.4",
    "memvid-sdk>=2.0.156",
    "pypdf>=6.7.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]
